image:
  repository: public.ecr.aws/p5v6t9h8
  pullPolicy: IfNotPresent

serviceAccount:
  # Specifies whether a service account should be created
  create: true

# client id, contact webb.ai to get a clientID
clientID: ""
# api key, contact webb.ai to get a API key
apiKey: ""

resourceCollector:
  kafka:
    # list of bootstrap servers for kafka, separated by comma
    servers: ""
  resources:
    requests:
      memory: 1000Mi
      cpu: 300m
    limits:
      memory: 2000Mi
      cpu: 500m

trafficCollector:
  resources:
    requests:
      memory: 200Mi
      cpu: 300m
    limits:
      memory: 1000Mi
      cpu: 500m

# whether to redact env variables
# if true, env variables in containers and initContainers of pods, deployments, daemonsets, statefulsets, job, and cronjobs will be masked before sending to webb.ai
redactEnvVar: false
