---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: webbai-traffic-collector
  name: webbai-traffic-collector
spec:
  selector:
    matchLabels:
      app: webbai-traffic-collector
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /webbai_metrics
        prometheus.io/port: "9095"
      labels:
        app: webbai-traffic-collector
      name: webbai-traffic-collector
    spec:
      containers:
        - command:
            - ./worker
            - -i
            - any
            - -port
            - "8897"
            - -metrics-port
            - "9095"
            - -packet-capture
            - libpcap
            - -servicemesh
            - -tls
            - -procfs
            - /hostproc
          image: "{{ .Values.image.repository }}/k8s-traffic-collector:v0.8.3.2"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: webbai-traffic-collector
          env:
            - name: GOGC
              value: '50'
          ports:
            - containerPort: 8897
              hostPort: 8897
            - containerPort: 9095
              hostPort: 9095
          resources:
            {{- toYaml .Values.trafficCollector.resources | nindent 12 }}
          securityContext:
            capabilities:
              add:
                - NET_RAW
                - NET_ADMIN
                - SYS_ADMIN
                - SYS_PTRACE
                - DAC_OVERRIDE
                - SYS_RESOURCE
              drop:
                - ALL
          volumeMounts:
            - mountPath: /hostproc
              name: proc
              readOnly: true
            - mountPath: /sys
              name: sys
              readOnly: true
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      serviceAccountName: webbai
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "eks.amazonaws.com/compute-type"
                  operator: NotIn
                  values: ["fargate"]
      terminationGracePeriodSeconds: 0
      {{- with .Values.trafficCollector.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - hostPath:
            path: /proc
          name: proc
        - hostPath:
            path: /sys
          name: sys
